-- Daily Ad Review: replaces the "DAILY AD REVIEW" Google Sheet.
--
--   ad_review_ads        one row per Meta ad   (sheet: AD LIST)
--   ad_review_snapshots  one row per ad per Meta report date
--                        (sheet: <MONTH> REVIEW grids + DATA LOG)
--   ad_review_actions    the "ACTION (fill in)" note per ad per report (sheet: AD REPORT)
--   ad_review_leads      Meta lead-form submissions   (sheet: LEADS)
--   ad_review_playbook   the editable playbook and decision rules (sheet: SOP)
--
-- Leads hold names, emails and phone numbers, so every table is signed-in staff only.
-- Safe to re-run. Run in the Supabase SQL editor.

create table if not exists public.ad_review_ads (
  id bigint generated by default as identity primary key,
  ad_name text not null unique,
  campaign text,
  ad_set text,
  published_on date,
  status text not null default 'ACTIVE' check (status in ('ACTIVE', 'INACTIVE')),
  workflow_stage text check (workflow_stage in ('Reported', 'Recommended', 'Approved', 'Acted')),
  owner_notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.ad_review_snapshots (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ad_review_ads (id) on delete cascade,
  report_date date not null,
  range_start date,
  impressions integer not null default 0,
  amount_spent numeric(12, 2) not null default 0,
  leads integer not null default 0,
  ctr_all numeric(10, 8) not null default 0,  -- fraction: 0.0192 = 1.92%
  ctr_lct numeric(10, 8) not null default 0,
  imported_ad_name text,                       -- name as it appeared in the Meta export
  delivery text,                               -- Meta "Ad delivery" on that report (active / inactive / …)
  imported_at timestamptz not null default now(),
  imported_by text default (auth.jwt() ->> 'email'),
  unique (ad_id, report_date)
);

create table if not exists public.ad_review_actions (
  id bigint generated by default as identity primary key,
  ad_id bigint not null references public.ad_review_ads (id) on delete cascade,
  report_date date not null,
  action text not null,
  updated_at timestamptz not null default now(),
  updated_by text default (auth.jwt() ->> 'email'),
  unique (ad_id, report_date)
);

create table if not exists public.ad_review_leads (
  id text primary key,                         -- Meta lead id, e.g. l:1992563191438377
  created_time timestamptz,
  ad_name text,
  adset_name text,
  campaign_name text,
  form_name text,
  platform text,
  email text,
  phone text,
  first_name text,
  last_name text,
  imported_at timestamptz not null default now()
);

-- The Playbook tab (sheet: SOP): one editable document. Its "rules" numbers drive the Hub's diagnosis.
create table if not exists public.ad_review_playbook (
  id integer primary key default 1 check (id = 1),
  content jsonb not null,
  updated_at timestamptz not null default now(),
  updated_by text default (auth.jwt() ->> 'email')
);

-- Every save records who made it and when, set by the database.
create or replace function public.ad_review_playbook_stamp()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  new.updated_by := auth.jwt() ->> 'email';
  return new;
end
$$;

drop trigger if exists ad_review_playbook_stamp on public.ad_review_playbook;
create trigger ad_review_playbook_stamp
  before insert or update on public.ad_review_playbook
  for each row execute function public.ad_review_playbook_stamp();

create index if not exists ad_review_snapshots_date_idx on public.ad_review_snapshots (report_date);
create index if not exists ad_review_leads_created_idx on public.ad_review_leads (created_time);

-- Signed-in staff only.
do $$
declare
  t text;
begin
  foreach t in array array['ad_review_ads', 'ad_review_snapshots', 'ad_review_actions', 'ad_review_leads', 'ad_review_playbook'] loop
    execute format('revoke all on table public.%I from anon', t);
    execute format('alter table public.%I enable row level security', t);
    execute format('drop policy if exists "Staff manage %1$s" on public.%1$I', t);
    execute format(
      'create policy "Staff manage %1$s" on public.%1$I for all to authenticated using (true) with check (true)',
      t
    );
    execute format('grant select, insert, update, delete on table public.%I to authenticated', t);
  end loop;
end
$$;
