-- Red / Orange Follow-Up: contact log. One row per call attempt, kept across reports,
-- so a member stays "contacted" until they train again. Run after follow_up_reports.sql.
--
-- Holds member names and phone numbers: signed-in staff only. Safe to re-run.

create table if not exists public.follow_up_contacts (
  id bigint generated by default as identity primary key,
  member_key text not null,                -- member name, lower-case (same key as report notes)
  member_name text not null,
  phone text,
  tier text,                               -- orange | red | none, at the time of the call
  days int,                                -- days since last class, at the time of the call
  outcome text not null check (outcome in ('spoke', 'voicemail', 'no_answer', 'text', 'wrong_number')),
  note text check (char_length(note) <= 500),
  report_id bigint references public.follow_up_reports (id) on delete set null,
  contacted_at timestamptz not null default now(),
  contacted_by text
);

create index if not exists follow_up_contacts_member_idx on public.follow_up_contacts (member_key, contacted_at desc);
create index if not exists follow_up_contacts_when_idx on public.follow_up_contacts (contacted_at desc);

-- Who made the call is stamped by the database, not sent by the page.
create or replace function public.follow_up_contacts_stamp()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.contacted_by := auth.jwt() ->> 'email';
  return new;
end
$$;

drop trigger if exists follow_up_contacts_stamp on public.follow_up_contacts;
create trigger follow_up_contacts_stamp
  before insert or update on public.follow_up_contacts
  for each row execute function public.follow_up_contacts_stamp();

revoke all on table public.follow_up_contacts from anon;
alter table public.follow_up_contacts enable row level security;

drop policy if exists "Staff manage follow_up_contacts" on public.follow_up_contacts;
create policy "Staff manage follow_up_contacts" on public.follow_up_contacts
  for all to authenticated using (true) with check (true);

grant select, insert, update, delete on table public.follow_up_contacts to authenticated;
