-- Red / Orange Follow-Up Report (replaces the Attendance Report).
--
-- One row per generated report. Each keeps the inputs it was built from, so a
-- newer membership file can be run against the same attendance (and vice versa),
-- and the hand-written notes, so they carry forward when the report is regenerated.
--
-- Holds member names and phone numbers: signed-in staff only. Safe to re-run.

create table if not exists public.follow_up_reports (
  id bigint generated by default as identity primary key,
  report_date date not null,
  attendance_file text,
  membership_file text,
  attendance jsonb not null,                  -- [{ name, phone, lastAtt, status }]
  memberships jsonb not null,                 -- latest record per person: [{ name, label, status, begin, end }]
  notes jsonb not null default '{}'::jsonb,   -- { "member name (lower-case)": "note" }
  removed jsonb not null default '[]'::jsonb, -- member names taken off this report by hand
  created_at timestamptz not null default now(),
  created_by text default (auth.jwt() ->> 'email'),
  updated_at timestamptz not null default now(),
  updated_by text default (auth.jwt() ->> 'email')
);

create index if not exists follow_up_reports_created_idx on public.follow_up_reports (created_at desc);

-- Who last changed a report (notes, removals) is stamped by the database.
create or replace function public.follow_up_reports_stamp()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at := now();
  new.updated_by := auth.jwt() ->> 'email';
  return new;
end
$$;

drop trigger if exists follow_up_reports_stamp on public.follow_up_reports;
create trigger follow_up_reports_stamp
  before update on public.follow_up_reports
  for each row execute function public.follow_up_reports_stamp();

revoke all on table public.follow_up_reports from anon;
alter table public.follow_up_reports enable row level security;

drop policy if exists "Staff manage follow_up_reports" on public.follow_up_reports;
create policy "Staff manage follow_up_reports" on public.follow_up_reports
  for all to authenticated using (true) with check (true);

grant select, insert, update, delete on table public.follow_up_reports to authenticated;
