create table if not exists public.past_due_member_log (
  id bigint generated by default as identity primary key,
  member_key text not null unique,
  member_name text not null,
  member_number text,
  bill_type text,
  first_name text,
  last_name text,
  income_category text,
  email text,
  due_date text,
  amount_due numeric,
  amount numeric,
  days_overdue integer,
  stage text,
  failure_reason text,
  last_payment_retry text,
  last_contact_date text,
  outcome_notes text,
  escalated_to_darius boolean not null default false,
  class_blocked boolean not null default false,
  autopay text,
  autopay_account text,
  status text not null default 'PAST DUE',
  imported_at timestamptz not null default now(),
  raw_data jsonb not null default '{}'::jsonb
);

alter table public.past_due_member_log add column if not exists bill_type text;
alter table public.past_due_member_log add column if not exists first_name text;
alter table public.past_due_member_log add column if not exists last_name text;
alter table public.past_due_member_log add column if not exists income_category text;
alter table public.past_due_member_log add column if not exists due_date text;
alter table public.past_due_member_log add column if not exists amount_due numeric;
alter table public.past_due_member_log add column if not exists autopay text;
alter table public.past_due_member_log add column if not exists autopay_account text;
alter table public.past_due_member_log add column if not exists failure_reason text;
alter table public.past_due_member_log add column if not exists last_payment_retry text;
alter table public.past_due_member_log add column if not exists last_contact_date text;
alter table public.past_due_member_log add column if not exists outcome_notes text;
alter table public.past_due_member_log add column if not exists escalated_to_darius boolean not null default false;
alter table public.past_due_member_log add column if not exists class_blocked boolean not null default false;

alter table public.past_due_member_log enable row level security;

create policy "Authenticated users can read past due member log"
  on public.past_due_member_log for select
  to authenticated
  using (true);

create policy "Authenticated users can insert past due member log"
  on public.past_due_member_log for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update past due member log"
  on public.past_due_member_log for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can delete past due member log"
  on public.past_due_member_log for delete
  to authenticated
  using (true);

create table if not exists public.past_due_exempted_members (
  id bigint generated by default as identity primary key,
  member_key text not null unique,
  member_name text,
  member_number text,
  first_name text,
  last_name text,
  membership_label text,
  mbr_status text,
  mbr_begin_date text,
  mbr_end_date text,
  att_limit text,
  att_limit_type text,
  people_count text,
  autopay text,
  note text,
  created_at timestamptz not null default now()
);

alter table public.past_due_exempted_members add column if not exists first_name text;
alter table public.past_due_exempted_members add column if not exists last_name text;
alter table public.past_due_exempted_members add column if not exists membership_label text;
alter table public.past_due_exempted_members add column if not exists mbr_status text;
alter table public.past_due_exempted_members add column if not exists mbr_begin_date text;
alter table public.past_due_exempted_members add column if not exists mbr_end_date text;
alter table public.past_due_exempted_members add column if not exists att_limit text;
alter table public.past_due_exempted_members add column if not exists att_limit_type text;
alter table public.past_due_exempted_members add column if not exists people_count text;
alter table public.past_due_exempted_members add column if not exists autopay text;
alter table public.past_due_exempted_members add column if not exists note text;

alter table public.past_due_exempted_members enable row level security;

create policy "Authenticated users can read exempted members"
  on public.past_due_exempted_members for select
  to authenticated
  using (true);

create policy "Authenticated users can insert exempted members"
  on public.past_due_exempted_members for insert
  to authenticated
  with check (true);

create policy "Authenticated users can update exempted members"
  on public.past_due_exempted_members for update
  to authenticated
  using (true)
  with check (true);

create policy "Authenticated users can delete exempted members"
  on public.past_due_exempted_members for delete
  to authenticated
  using (true);

create table if not exists public.membership_weekly_log (
  id bigint generated by default as identity primary key,
  report_date date,
  members_total numeric,
  regular_adult numeric,
  beginner_adult numeric,
  concession_adult numeric,
  chiisai_kai numeric,
  kids_8_14 numeric,
  kids_15_17 numeric,
  blue_zone numeric,
  combat_pilates numeric,
  beginner_totals numeric,
  become_adult numeric,
  become_chiisai numeric,
  become_kids numeric,
  become_blue_zone numeric,
  become_c_pilates numeric,
  uploaded_at timestamptz default now(),
  snapshot_label text default 'CURRENT'
);

alter table public.membership_weekly_log enable row level security;

drop policy if exists "Authenticated users can read weekly membership log" on public.membership_weekly_log;
create policy "Authenticated users can read weekly membership log"
  on public.membership_weekly_log for select
  to authenticated
  using (true);

drop policy if exists "Authenticated users can insert weekly membership log" on public.membership_weekly_log;
create policy "Authenticated users can insert weekly membership log"
  on public.membership_weekly_log for insert
  to authenticated
  with check (true);

drop policy if exists "Authenticated users can update weekly membership log" on public.membership_weekly_log;
create policy "Authenticated users can update weekly membership log"
  on public.membership_weekly_log for update
  to authenticated
  using (true)
  with check (true);

drop policy if exists "Authenticated users can delete weekly membership log" on public.membership_weekly_log;
create policy "Authenticated users can delete weekly membership log"
  on public.membership_weekly_log for delete
  to authenticated
  using (true);