-- Member-level notes for the Past Due report.
--
-- One running notes thread per member, shared across all of that member's
-- bills. Replaces the old per-bill "Notes / Updates" field. Members are matched
-- the same way the page groups bills: by name, trimmed, lower-cased, with
-- repeated spaces collapsed.
--
-- Safe to re-run. Run in the Supabase SQL editor.

create table if not exists public.past_due_member_notes (
  id bigint generated by default as identity primary key,
  member_identity text not null,
  member_name text,
  note text not null check (char_length(btrim(note)) between 1 and 2000),
  author text default (auth.jwt() ->> 'email'),
  created_at timestamptz not null default now()
);

create index if not exists past_due_member_notes_member_idx
  on public.past_due_member_notes (member_identity, created_at desc);

-- Signed-in staff only. Everyone can read and add notes; the author is set by
-- the database from the session, and only the author can delete a note.
revoke all on table public.past_due_member_notes from anon;
alter table public.past_due_member_notes enable row level security;

drop policy if exists "Staff read member notes" on public.past_due_member_notes;
create policy "Staff read member notes" on public.past_due_member_notes
  for select to authenticated using (true);

drop policy if exists "Staff add member notes" on public.past_due_member_notes;
create policy "Staff add member notes" on public.past_due_member_notes
  for insert to authenticated with check (author = auth.jwt() ->> 'email');

drop policy if exists "Staff delete own member notes" on public.past_due_member_notes;
create policy "Staff delete own member notes" on public.past_due_member_notes
  for delete to authenticated using (author = auth.jwt() ->> 'email');

grant select, insert, delete on table public.past_due_member_notes to authenticated;

-- Editing: any staff member can edit a note's text. The database stamps who
-- edited it and when, and keeps the original author, member and date as-is.
alter table public.past_due_member_notes add column if not exists edited_by text;
alter table public.past_due_member_notes add column if not exists edited_at timestamptz;

create or replace function public.past_due_member_notes_stamp_edit()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.id := old.id;
  new.member_identity := old.member_identity;
  new.member_name := old.member_name;
  new.author := old.author;
  new.created_at := old.created_at;
  new.edited_by := auth.jwt() ->> 'email';
  new.edited_at := now();
  return new;
end
$$;

drop trigger if exists past_due_member_notes_stamp_edit on public.past_due_member_notes;
create trigger past_due_member_notes_stamp_edit
  before update on public.past_due_member_notes
  for each row execute function public.past_due_member_notes_stamp_edit();

drop policy if exists "Staff edit member notes" on public.past_due_member_notes;
create policy "Staff edit member notes" on public.past_due_member_notes
  for update to authenticated using (true) with check (true);

grant update (note) on table public.past_due_member_notes to authenticated;

-- Carry the old per-bill notes into each member's thread (skips any already copied).
alter table public.past_due_member_log add column if not exists notes text;

with old as (
  select
    lower(regexp_replace(btrim(member_name), '\s+', ' ', 'g')) as member_identity,
    member_name,
    left('Bill #' || coalesce(member_number, '?') || ': '
      || coalesce(nullif(btrim(notes), ''), btrim(outcome_notes)), 2000) as note,
    imported_at
  from public.past_due_member_log
  where coalesce(nullif(btrim(notes), ''), nullif(btrim(outcome_notes), '')) is not null
)
insert into public.past_due_member_notes (member_identity, member_name, note, author, created_at)
select o.member_identity, o.member_name, o.note, 'Earlier bill note', o.imported_at
from old o
where not exists (
  select 1 from public.past_due_member_notes n
  where n.member_identity = o.member_identity and n.note = o.note
);
